name: Super-Linter

on:
  push:
    branches:
      - master # Change this to your main branch

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Checkout code
        run: echo "Hello World"
        shell: bash



     
