name: Build React App

on:
  push:
    branches:
      - master # Change to the main branch or your default branch

jobs:
  build:
    runs-on: ubuntu-latest  # You can choose a different runner if needed

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 18

    - name: Install dependencies
      run: npm install

    - name: Test vite
      run: npm run test

    - name: Configure Vite
      run: | 
        echo 'export default { build: { outDir: "build" } };' > vite.config.js

    - name: Build React App
      run: npm run build

    - name: Create Artifact
      uses: actions/upload-artifact@v2
      with:
        name: build-artifact
        path: build
    
    - name: Download Artifact
      uses: actions/download-artifact@v2
      with:
        name: build-artifact
        path: artifacts

    - name: Create ZIP Archive
      run: zip -r my-artifact.zip . -i /home/runner/work/githubActionsTest/githubActionsTest/artifact

    - name: Upload ZIP Archive
      uses: actions/upload-artifact@v2
      with:
        name: build-artifact-zip
        path: build-artifact.zip

